---
abstract: 'Number::Format::SouthAsian provides methods to format numbers in the South Asian style.'
author:
  - 'Alex Balhatchet (alex@lokku.com)'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.031, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Number-Format-SouthAsian
requires:
  Carp: '0'
  English: '0'
  ExtUtils::MakeMaker: '0'
  Scalar::Util: '0'
resources:
  repository: git://github.com/lokku/Number-Format-SouthAsian.git
version: '0.10'
